const STORE_KEY = 'ROUTE';

export const FETCH_ROUTE_REQUEST = `${STORE_KEY}/FETCH_ROUTE_REQUEST`;
export const FETCH_ROUTE_SUCCESS = `${STORE_KEY}/FETCH_ROUTE_SUCCESS`;
export const FETCH_ROUTE_FAILURE = `${STORE_KEY}/FETCH_ROUTE_FAILURE`;
export const FETCH_NEW_ROUTE_REQUEST = `${STORE_KEY}/FETCH_NEW_ROUTE_REQUEST`;