const STORE_KEY = "AUTH";

export const FETCH_AUTH_REQUEST = `${STORE_KEY}/FETCH_AUTH_REQUEST`;
export const FETCH_AUTH_SUCCESS = `${STORE_KEY}/FETCH_AUTH_SUCCESS`;
export const FETCH_AUTH_FAILURE = `${STORE_KEY}/FETCH_AUTH_FAILURE`;
export const FETCH_LOGOUT_REQUEST = `${STORE_KEY}/FETCH_LOGOUT_REQUEST`;