const STORE_KEY = "PROFILE";

export const FETCH_PROFILE_REQUEST = `${STORE_KEY}/FETCH_PROFILE_REQUEST`;
export const FETCH_PROFILE_SUCCESS = `${STORE_KEY}/FETCH_PROFILE_SUCCESS`;
export const FETCH_PROFILE_FAILURE = `${STORE_KEY}/FETCH_PROFILE_FAILURE`;