const STORE_KEY = 'MAP';

export const FETCH_MAP_REQUEST = `${STORE_KEY}/FETCH_MAP_REQUEST`;
export const FETCH_MAP_SUCCESS = `${STORE_KEY}/FETCH_MAP_SUCCESS`;
export const FETCH_MAP_FAILURE = `${STORE_KEY}/FETCH_MAP_FAILURE`;

export const FETCH_ADDRESS_LIST_REQUEST = `${STORE_KEY}/FETCH_ADDRESS_LIST_REQUEST`;
export const FETCH_ADDRESS_LIST_SUCCESS = `${STORE_KEY}/FETCH_ADDRESS_LIST_SUCCESS`;
export const FETCH_ADDRESS_LIST_FAILURE = `${STORE_KEY}/FETCH_ADDRESS_LIST_FAILURE`;